name: roomate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  auto_route: ^10.3.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  import_sorter: ^4.6.0
  intl: ^0.20.2
  flutter_image_carousel_slider: ^2.0.1
  dropdown_button2: ^2.3.9
  flutter_bloc: ^9.1.1
  group_button: ^5.3.4
  freezed_annotation: ^3.1.0
  freezed: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  auto_route_generator: 10.3.0


flutter:
  generate: true
  uses-material-design: true
  assets:
  - lib/presentation/assets/icons/
  fonts:
    - family: Helvetica
      fonts:
        - asset: lib/presentation/assets/fonts/helvetica-neue-bold.ttf
          weight: 700
        - asset: lib/presentation/assets/fonts/helvetica-neue-regular.ttf
          weight: 400
        - asset: lib/presentation/assets/fonts/helvetica-neue-medium.ttf
          weight: 500



import_sorter:
  emojis: false
  comments: false
  ignored_files:
  - lib/presentation/l10n/*
  - lib/presentation/routing/*
  - r".*g\.dart$"
  - r".*gr\.dart$"
  - r".*freezed\.dart$"

