name: domain
description: "Domain layer for Roomate"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.10.0"

dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  freezed: ^3.2.5
  import_sorter: ^4.6.0
  json_annotation: ^4.11.0
  shared:
    path: ../shared
  data:
    path: ../data
dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  json_serializable: ^6.11.1

import_sorter:
  emojis: false
  comments: false
  ignored_files:
    - lib/l10n/*
    - lib/routing/*
    - r".*g\.dart$"
    - r".*gr\.dart$"
    - r".*freezed\.dart$"
